const SKILLS = {
  interpersonal: {
    leadership: {
      icon: "",
      title: "Leadership",
    },
		strategicPlanning : {icon: "", title: "",},
		teamwork : {icon: "", title: "",},
		publicSpeaking : {icon: "", title: "",},
		communication : {icon: "", title: "",},
		teamLeadership : {icon: "", title: "",},
		decisionMaking : {icon: "", title: "",},
		problemResolution : {icon: "", title: "",},
		relationshipBuilding : {icon: "", title: "",},
		complexProblemSolving : {icon: "", title: "",},
  },
	toolsTechnologies : {
		googleCloudPlatform : {icon: "", title: "",},
		cpp : {icon: "", title: "",},
		unity : {icon: "", title: "",},
		java : {icon: "", title: "",},
		nodeJs : {icon: "", title: "",},
		javascript : {icon: "", title: "",},
		express : {},
		html5 : {icon: "", title: "",},
		matlab : {icon: "", title: "",},
		python : {icon: "", title: "",},
		linux : {icon: "", title: "",},
		verilog : {icon: "", title: "",},
		react : {icon: "", title: "",},
		git : {icon: "", title: "",},
		css : {icon: "", title: "",},
		sql : {icon: "", title: "",},
		mongoDb : {icon: "", title: "",},
		graphQl : {icon: "", title: "",},
		solidity : {icon: "", title: "",},
	},
	industryKnowledge :{
		communityOutreach : {icon: "", title: "",},
		clientRelationships : {icon: "", title: "",},
		customerRelations : {icon: "", title: "",},
		publicRelations : {icon: "", title: "",},
		microControllers : {icon: "", title: "",},
		electricalEngineering : {icon: "", title: "",},
		agile : {icon: "", title: "",},
		qualityAssurance : {icon: "", title: "",},
		customerService : {icon: "", title: "",},
		processImprovement : {icon: "", title: "",},
		designSpecifications : {icon: "", title: "",},
	}
};
